greet=["Hello",
"Hi there",
"Hey ",
"Greetings",
"Howdy",
"Good day",
"What's up",
"Hi, friend",
"How's it going",
"Salutations",
"Yo ",
"Hi, there",
"Hi, stranger",
"Hi, pal",
"Aloha",
"Hi "]


closing_phrases = [
    "Goodbye.",
    "I'm signing off now.",
    "That's all for now. Bye!",
    "Thank you for your help!",
    "I appreciate your assistance.",
    "Thanks, that was helpful.",
    "I got the information I needed.",
    "You answered my question.",
    "I'm done here.",
    "Can we end the conversation?",
    "Is there anything else I can assist with?",
    "I think we're finished, right?",
    "It was nice talking to you.",
    "Have a great day!",
    "Take care.",
    "Catch you later!",
    "Gotta go now.",
    "Bye for now!"
]


thankful = [
    "Thank you for your help.",
    "I appreciate your assistance.",
    "You've been very helpful.",
    "Thanks so much!",
    "You're awesome!",
    "Great job!",
    "I'm grateful for your support.",
    "You made my day!",
    "You've been a lifesaver.",
    "I owe you one.",
    "I can't thank you enough.",
    "You're a star!",
    "I'm so thankful for your help.",
    "You're the best!",
    "You're amazing!",
    "I'm indebted to you.",
    "You've been a tremendous help.",
    "You're a real gem!",
    "I'm filled with gratitude.",
    "You're a true friend.",
]